--DROP CONSTRAINT SO THAT DEFAULT INDEXES ARE NOT CREATED
ALTER TABLE EXAM_RESULTS DROP CONSTRAINT STUDENT_FK;
ALTER TABLE EXAM_RESULTS DROP CONSTRAINT SUBJECT_FK;

ALTER TABLE SUBJECTS DROP CONSTRAINT SUBJECTS_PKEY;
ALTER TABLE STUDENTS DROP CONSTRAINT STUDENTS_PKEY;

--DISABLE SCANS
SET ENABLE_BITMAPSCAN TO ON;
SET ENABLE_BITMAPSCAN TO OFF;
SET ENABLE_SEQSCAN = ON;
SET ENABLE_SEQSCAN = OFF;


EXPLAIN (ANALYZE) SELECT * FROM STUDENTS WHERE FIRSTNAME = 'Alice';

EXPLAIN (ANALYZE) SELECT * FROM STUDENTS WHERE FIRSTNAME = 'Logan';

EXPLAIN (ANALYZE) SELECT * FROM STUDENTS WHERE SURNAME LIKE '%Buck%';

EXPLAIN (ANALYZE) SELECT * FROM STUDENTS WHERE SURNAME LIKE '%il%';

EXPLAIN (ANALYZE) SELECT * FROM STUDENTS WHERE PHONE_NUMBER LIKE '%184%';

EXPLAIN (ANALYZE) SELECT * FROM STUDENTS WHERE PHONE_NUMBER LIKE '%38%';

EXPLAIN (ANALYZE)
SELECT ST.*, S.TITLE, ER.MARK FROM STUDENTS ST 
JOIN EXAM_RESULTS ER
ON ST.ID = ER.STUDENT_ID
JOIN SUBJECTS S
ON S.ID = ER.SUBJECT_ID
WHERE ST.SURNAME LIKE '%Buck%';

EXPLAIN (ANALYZE)
SELECT ST.*, S.TITLE, ER.MARK FROM STUDENTS ST 
JOIN EXAM_RESULTS ER
ON ST.ID = ER.STUDENT_ID
JOIN SUBJECTS S
ON S.ID = ER.SUBJECT_ID
WHERE ST.SURNAME LIKE '%il%';

SELECT PG_SIZE_PRETTY (PG_INDEXES_SIZE('STUDENTS'));
SELECT PG_SIZE_PRETTY (PG_INDEXES_SIZE('SUBJECTS'));
SELECT PG_SIZE_PRETTY (PG_INDEXES_SIZE('EXAM_RESULTS'));
