-- IMPORT STUDENTS

COPY STUDENTS(FIRSTNAME, SURNAME, DATE_OF_BIRTH, PHONE_NUMBER, PRIMARY_SKILL)
FROM '/data/students.csv'
DELIMITER ','
CSV HEADER;

SELECT COUNT(1) FROM STUDENTS;

-- IMPORT SUBJECTS

COPY SUBJECTS(TITLE, TUTOR_NAME)
FROM '/data/subjects.csv'
DELIMITER ','
CSV HEADER;

SELECT COUNT(1) FROM SUBJECTS;

-- IMPORT MARKS

COPY EXAM_RESULTS(STUDENT_ID, SUBJECT_ID, MARK)
FROM '/data/marks.csv'
DELIMITER ','
CSV HEADER;

SELECT COUNT(1) FROM EXAM_RESULTS;






