--BTREE
--DROP INDEX STUDENT_NAME_BTREE_IDX;
CREATE INDEX STUDENT_FIRSTNAME_BTREE_IDX ON STUDENTS USING BTREE (FIRSTNAME);
--DROP INDEX STUDENT_SURNAME_BTREE_IDX;
CREATE INDEX STUDENT_SURNAME_BTREE_IDX ON STUDENTS USING BTREE (SURNAME);
--DROP INDEX STUDENT_PHONE_NUMBER_BTREE_IDX;
CREATE INDEX STUDENT_PHONE_NUMBER_BTREE_IDX ON STUDENTS USING BTREE (PHONE_NUMBER);
--DROP INDEX STUDENT_ID_BTREE_IDX;
CREATE INDEX STUDENT_ID_BTREE_IDX ON STUDENTS USING BTREE (ID);
--DROP INDEX SUBJECT_ID_BTREE_IDX;
CREATE INDEX SUBJECT_ID_BTREE_IDX ON SUBJECTS USING BTREE (ID);
--DROP INDEX EXAM_RESULTS_STUDENT_ID_BTREE_IDX;
CREATE INDEX EXAM_RESULTS_STUDENT_ID_BTREE_IDX ON EXAM_RESULTS USING BTREE (STUDENT_ID);
--DROP INDEX EXAM_RESULTS_SUBJECT_ID_BTREE_IDX;
CREATE INDEX EXAM_RESULTS_SUBJECT_ID_BTREE_IDX ON EXAM_RESULTS USING BTREE (SUBJECT_ID);

--HASH
--DROP INDEX STUDENT_FIRSTNAME_HASH_IDX;
CREATE INDEX STUDENT_FIRSTNAME_HASH_IDX ON STUDENTS USING HASH (FIRSTNAME);
--DROP INDEX STUDENT_SURNAME_HASH_IDX;
CREATE INDEX STUDENT_SURNAME_HASH_IDX ON STUDENTS USING HASH (SURNAME);
--DROP INDEX STUDENT_PHONE_NUMBER_HASH_IDX;
CREATE INDEX STUDENT_PHONE_NUMBER_HASH_IDX ON STUDENTS USING HASH (PHONE_NUMBER);
--DROP INDEX STUDENT_ID_HASH_IDX;
CREATE INDEX STUDENT_ID_HASH_IDX ON STUDENTS USING HASH (ID);
--DROP INDEX SUBJECT_ID_HASH_IDX;
CREATE INDEX SUBJECT_ID_HASH_IDX ON SUBJECTS USING HASH (ID);
--DROP INDEX EXAM_RESULTS_STUDENT_ID_HASH_IDX;
CREATE INDEX EXAM_RESULTS_STUDENT_ID_HASH_IDX ON EXAM_RESULTS USING HASH (STUDENT_ID);
--DROP INDEX EXAM_RESULTS_SUBJECT_ID_HASH_IDX;
CREATE INDEX EXAM_RESULTS_SUBJECT_ID_HASH_IDX ON EXAM_RESULTS USING HASH (SUBJECT_ID);

--GIN
--DROP EXTENSION PG_TRGM;
CREATE EXTENSION PG_TRGM;
--DROP EXTENSION BTREE_GIN;
CREATE EXTENSION BTREE_GIN;

--DROP INDEX STUDENT_FIRSTNAME_GIN_IDX;
CREATE INDEX STUDENT_FIRSTNAME_GIN_IDX ON STUDENTS USING GIN (FIRSTNAME GIN_TRGM_OPS);
--DROP INDEX STUDENT_SURNAME_GIN_IDX;
CREATE INDEX STUDENT_SURNAME_GIN_IDX ON STUDENTS USING GIN (SURNAME GIN_TRGM_OPS);
--DROP INDEX STUDENT_PHONE_NUMBER_GIN_IDX;
CREATE INDEX STUDENT_PHONE_NUMBER_GIN_IDX ON STUDENTS USING GIN (PHONE_NUMBER GIN_TRGM_OPS);
--DROP INDEX STUDENT_ID_GIN_IDX;
CREATE INDEX STUDENT_ID_GIN_IDX ON STUDENTS USING GIN (ID);
--DROP INDEX SUBJECT_ID_GIN_IDX;
CREATE INDEX SUBJECT_ID_GIN_IDX ON SUBJECTS USING GIN (ID);
--DROP INDEX EXAM_RESULTS_STUDENT_ID_GIN_IDX;
CREATE INDEX EXAM_RESULTS_STUDENT_ID_GIN_IDX ON EXAM_RESULTS USING GIN (STUDENT_ID);
--DROP INDEX EXAM_RESULTS_SUBJECT_ID_GIN_IDX;
CREATE INDEX EXAM_RESULTS_SUBJECT_ID_GIN_IDX ON EXAM_RESULTS USING GIN (SUBJECT_ID);

--GIST
--DROP EXTENSION BTREE_GIST;
CREATE EXTENSION BTREE_GIST;

--DROP INDEX STUDENT_FIRSTNAME_GIST_IDX;
CREATE INDEX STUDENT_FIRSTNAME_GIST_IDX ON STUDENTS USING GIST (FIRSTNAME);
--DROP INDEX STUDENT_SURNAME_GIST_IDX;
CREATE INDEX STUDENT_SURNAME_GIST_IDX ON STUDENTS USING GIST (SURNAME);
--DROP INDEX STUDENT_PHONE_NUMBER_GIST_IDX;
CREATE INDEX STUDENT_PHONE_NUMBER_GIST_IDX ON STUDENTS USING GIST (PHONE_NUMBER);
--DROP INDEX STUDENT_ID_GIST_IDX;
CREATE INDEX STUDENT_ID_GIST_IDX ON STUDENTS USING GIST (ID);
--DROP INDEX SUBJECT_ID_GIST_IDX;
CREATE INDEX SUBJECT_ID_GIST_IDX ON SUBJECTS USING GIST (ID);
--DROP INDEX EXAM_RESULTS_STUDENT_ID_GIST_IDX;
CREATE INDEX EXAM_RESULTS_STUDENT_ID_GIST_IDX ON EXAM_RESULTS USING GIST (STUDENT_ID);
--DROP INDEX EXAM_RESULTS_SUBJECT_ID_GIST_IDX;
CREATE INDEX EXAM_RESULTS_SUBJECT_ID_GIST_IDX ON EXAM_RESULTS USING GIST (SUBJECT_ID);