--DROP SEQUENCE IF EXISTS STUDENT_ID_SEQ;

CREATE SEQUENCE STUDENT_ID_SEQ;

--DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS (
	ID 				BIGINT DEFAULT NEXTVAL('STUDENT_ID_SEQ'),
	FIRSTNAME		VARCHAR (255) NOT NULL,
	SURNAME			VARCHAR (255) NOT NULL,
	DATE_OF_BIRTH 	DATE NOT NULL,
	PHONE_NUMBER	VARCHAR (32),
	PRIMARY_SKILL	VARCHAR (32),
	CREATED			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED 		TIMESTAMP
);

--DROP SEQUENCE IF EXISTS SUBJECT_ID_SEQ;

CREATE SEQUENCE SUBJECT_ID_SEQ;

--DROP TABLE IF EXISTS SUBJECTS;

CREATE TABLE SUBJECTS (
	ID 				BIGINT DEFAULT NEXTVAL('SUBJECT_ID_SEQ'),
	TITLE			VARCHAR (255) NOT NULL,
	TUTOR_NAME		VARCHAR (255) NOT NULL,
	CREATED			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED 		TIMESTAMP
);

-- DROP TABLE IF EXISTS EXAM_RESULTS;

CREATE TABLE EXAM_RESULTS (
	STUDENT_ID 		BIGINT NOT NULL,
	SUBJECT_ID 		BIGINT NOT NULL,
	MARK			SMALLINT NOT NULL,
	CONSTRAINT STUDENT_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID),
	CONSTRAINT SUBJECT_FK FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID)	
);
