--DROP SEQUENCE IF EXISTS STUDENT_ID_SEQ;

CREATE SEQUENCE STUDENT_ID_SEQ;

--DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS (
	ID 				BIGINT PRIMARY KEY DEFAULT NEXTVAL('STUDENT_ID_SEQ'),
	FIRSTNAME		VARCHAR (255) NOT NULL,
	SURNAME			VARCHAR (255) NOT NULL,
	DATE_OF_BIRTH 	DATE NOT NULL,
	PHONE_NUMBER	VARCHAR (32),
	PRIMARY_SKILL	VARCHAR (32),
	CREATED			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED 		TIMESTAMP
	);

--DROP SEQUENCE IF EXISTS SUBJECT_ID_SEQ;

CREATE SEQUENCE SUBJECT_ID_SEQ;

--DROP TABLE IF EXISTS SUBJECTS;

CREATE TABLE SUBJECTS (
	ID 				BIGINT PRIMARY KEY DEFAULT NEXTVAL('SUBJECT_ID_SEQ'),
	TITLE			VARCHAR (255) NOT NULL,
	TUTOR_NAME		VARCHAR (255) NOT NULL,
	CREATED			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED 		TIMESTAMP
	);

-- DROP TABLE IF EXISTS EXAM_RESULTS;

CREATE TABLE EXAM_RESULTS (
	STUDENT_ID 		BIGINT NOT NULL,
	SUBJECT_ID 		BIGINT NOT NULL,
	MARK			SMALLINT NOT NULL,
	CONSTRAINT EXAM_RESULTS_PK PRIMARY KEY (STUDENT_ID, SUBJECT_ID),
	CONSTRAINT STUDENT_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID),
	CONSTRAINT SUBJECT_FK FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID)	
	);

--DROP INDEX STUDENTS_FIRSTNAME_SURNAME_IDX;
	
CREATE INDEX STUDENTS_FIRSTNAME_SURNAME_IDX ON STUDENTS (FIRSTNAME, SURNAME); 

--DROP INDEX SUBJECTS_TITLE_IDX;

CREATE INDEX SUBJECTS_TITLE_IDX ON SUBJECTS (TITLE);

--DROP INDEX SUBJECTS_TUTOR_NAME_IDX;

CREATE INDEX SUBJECTS_TUTOR_NAME_IDX ON SUBJECTS (TUTOR_NAME);
