CREATE TABLE STUDENTS (
	ID 				BIGINT PRIMARY KEY,
	FIRSTNAME		VARCHAR (255) NOT NULL,
	SURNAME			VARCHAR (255) NOT NULL,
	DATE_OF_BIRTH 	DATE NOT NULL,
	PHONE_NUMBER	VARCHAR (32),
	CREATED			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED 		TIMESTAMP
	);
	
CREATE TABLE SUBJECTS (
	ID 				BIGINT PRIMARY KEY,
	TITLE			VARCHAR (255) NOT NULL,
	TUTOR_NAME		VARCHAR (255) NOT NULL,
	CREATED			TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED 		TIMESTAMP
	);

CREATE TABLE EXAM_RESULTS (
	STUDENT_ID 		BIGINT NOT NULL,
	SUBJECT_ID 		BIGINT NOT NULL,
	MARK			SMALLINT NOT NULL,
	CONSTRAINT EXAM_RESULTS_PK PRIMARY KEY (STUDENT_ID, SUBJECT_ID),
	CONSTRAINT STUDENT_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID),
	CONSTRAINT SUBJECT_FK FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID)	
	);
	
CREATE INDEX ON STUDENTS (FIRSTNAME, SURNAME); 

CREATE INDEX ON SUBJECTS (TITLE);

CREATE INDEX ON SUBJECTS (TUTOR_NAME);
