CREATE OR REPLACE FUNCTION STUDENTS_UPDATE_TRG_FNC()
	RETURNS trigger 
	LANGUAGE plpgsql
	AS
	$$
	BEGIN
		NEW.UPDATED = CURRENT_TIMESTAMP;
	RETURN NEW;
	END;
	$$

CREATE TRIGGER STUDENTS_UPDATE_TRG
BEFORE UPDATE ON STUDENTS
FOR EACH ROW 
EXECUTE PROCEDURE STUDENTS_UPDATE_TRG_FNC();
